import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import React from "react";

const poppins = Poppins({
    variable: "--font-poppins",
    weight: '400',
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="h-screen w-screen bg-gradient-to-br from-[#F5F0E6] via-[#E8DCC6] to-[#D4B896]">
            {children}
        </div>
    );
}